# Generated by Django 4.2.27 on 2026-01-31 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeoff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Coach who approved/rejected the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='user',
            field=models.ForeignKey(help_text='User requesting time off', on_delete=django.db.models.deletion.CASCADE, related_name='timeoff_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['user', 'status'], name='timeoff_req_user_id_ae2129_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['start_date', 'end_date'], name='timeoff_req_start_d_f45964_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['status', 'created_at'], name='timeoff_req_status_b816b7_idx'),
        ),
    ]
