# Generated by Django 4.2.27 on 2026-01-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayInLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(help_text='Date the day in lieu is scheduled for')),
                ('original_scheduled_date', models.DateField(blank=True, help_text='Original scheduled date (if adjusted by coach)', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current status of the day in lieu', max_length=20)),
                ('is_manually_created', models.BooleanField(default=False, help_text='Whether this was manually created by a coach (not auto-generated)')),
                ('adjusted_at', models.DateTimeField(blank=True, help_text='When the day was adjusted', null=True)),
                ('adjustment_reason', models.TextField(blank=True, help_text='Reason for adjustment (if applicable)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='When the day was used', null=True)),
            ],
            options={
                'verbose_name_plural': 'Days in lieu',
                'db_table': 'days_in_lieu',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the holiday (e.g., 'Christmas Day', 'Independence Day')", max_length=100)),
                ('date', models.DateField(help_text='Date of the holiday')),
                ('description', models.TextField(blank=True, help_text='Additional information about the holiday')),
                ('requires_coverage', models.BooleanField(default=True, help_text='Whether this holiday requires on-call coverage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='OnCallShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(help_text='Date of the shift')),
                ('shift_type', models.CharField(choices=[('early_primary', 'Early Primary'), ('late_primary', 'Late Primary'), ('secondary', 'Secondary'), ('holiday', 'Holiday Coverage')], help_text='Type of on-call shift', max_length=20)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week', max_length=10)),
                ('start_time', models.TimeField(blank=True, help_text='Start time of shift (optional, for custom schedules)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time of shift (optional, for custom schedules)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the shift')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'oncall_shifts',
                'ordering': ['shift_date', 'shift_type'],
            },
        ),
    ]
