# Generated by Django 4.2.27 on 2026-01-31 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oncall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oncallshift',
            name='engineer',
            field=models.ForeignKey(help_text='Engineer assigned to this shift', on_delete=django.db.models.deletion.CASCADE, related_name='oncall_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oncallshift',
            name='holiday',
            field=models.ForeignKey(blank=True, help_text='Associated holiday (if this is holiday coverage)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='oncall.holiday'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date'], name='holidays_date_c1d23c_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['requires_coverage', 'date'], name='holidays_require_2b3eed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('name', 'date')},
        ),
        migrations.AddField(
            model_name='dayinlieu',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, help_text='Coach who adjusted this day in lieu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_days_in_lieu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayinlieu',
            name='oncall_shift',
            field=models.ForeignKey(blank=True, help_text='The on-call shift this compensates for (optional for manually created days)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days_in_lieu', to='oncall.oncallshift'),
        ),
        migrations.AddField(
            model_name='dayinlieu',
            name='user',
            field=models.ForeignKey(help_text='User receiving the day in lieu', on_delete=django.db.models.deletion.CASCADE, related_name='days_in_lieu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='oncallshift',
            index=models.Index(fields=['shift_date', 'engineer'], name='oncall_shif_shift_d_d55378_idx'),
        ),
        migrations.AddIndex(
            model_name='oncallshift',
            index=models.Index(fields=['engineer', 'shift_date'], name='oncall_shif_enginee_24fadc_idx'),
        ),
        migrations.AddIndex(
            model_name='oncallshift',
            index=models.Index(fields=['holiday'], name='oncall_shif_holiday_e4a994_idx'),
        ),
        migrations.AddIndex(
            model_name='oncallshift',
            index=models.Index(fields=['shift_type', 'shift_date'], name='oncall_shif_shift_t_db96be_idx'),
        ),
        migrations.AddIndex(
            model_name='dayinlieu',
            index=models.Index(fields=['user', 'status'], name='days_in_lie_user_id_e12113_idx'),
        ),
        migrations.AddIndex(
            model_name='dayinlieu',
            index=models.Index(fields=['scheduled_date'], name='days_in_lie_schedul_ba4056_idx'),
        ),
        migrations.AddIndex(
            model_name='dayinlieu',
            index=models.Index(fields=['status', 'scheduled_date'], name='days_in_lie_status_461fff_idx'),
        ),
        migrations.AddIndex(
            model_name='dayinlieu',
            index=models.Index(fields=['is_manually_created'], name='days_in_lie_is_manu_45f661_idx'),
        ),
    ]
