# Generated by Django 4.2.27 on 2026-02-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncall', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncallshift',
            name='shift_type',
            field=models.CharField(choices=[('early_primary', 'Early Primary'), ('late_primary', 'Late Primary'), ('secondary', 'Secondary'), ('early_secondary', 'Early Secondary'), ('late_secondary', 'Late Secondary'), ('holiday', 'Holiday Coverage')], help_text='Type of on-call shift', max_length=20),
        ),
    ]
