# Generated by Django 4.2.27 on 2026-03-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncall', '0003_alter_oncallshift_shift_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncallshift',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week (auto-calculated from shift_date if not provided)', max_length=10),
        ),
    ]
