# Generated by Django 4.2.27 on 2026-02-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_must_change_password_user_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oncall_eligible',
            field=models.BooleanField(default=True, help_text='Whether engineer is eligible for on-call rotation assignments'),
        ),
    ]
