# Generated by Django 4.2.27 on 2026-03-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_oncall_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's preferred timezone (e.g., 'America/Denver', 'Europe/London')", max_length=50),
        ),
    ]
